### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by rahmiddinasiydinov** [Jalilovking/audiophile#2]
![issue](https://user-images.githubusercontent.com/81851084/129855288-71e38b11-f340-4ca6-ae29-ce9b7167043f.png)
codes are written in proper way at all, but I recommend to use first "width=..." and then "max-width=...%".
other codes are well done

**Comment by Jalilovking** [comment]
ok i will correct it. Also it is not finished yet

**Comment by rahmiddinasiydinov** [comment]
got it, have a nice coding!
